apiVersion: v1
kind: Service
metadata:
  name: training-service
  namespace: {{ .Values.traineeId }}
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
