{{- if .Values.deployments.secretCreator.configuration.chart.auth.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deployments.secretCreator.configuration.chart.auth.secret.name }}
  namespace: {{ .Values.Block.InstanceId }}
type: Opaque
stringData:
  {{ .Values.deployments.secretCreator.configuration.chart.auth.secret.key }}: {{ .Values.deployments.secretCreator.configuration.chart.auth.password }}

{{- end }}
