{{- if .Values.deployments.nginx.variables.imagePullSecret.enabled }}
{{- if .Values.deployments.nginx.variables.imagePullSecret.create }}

apiVersion: blocks/v1beta1
kind: ChartDeployment
metadata:
  name: {{ .Values.deployments.nginx.variables.appname }}-{{ .Values.Block.InstanceId }}
  namespace: {{ .Values.Block.InstanceId }}
spec:
  template:
    metadata:
      labels:
        application: {{ .Values.deployments.nginx.variables.appname }}-{{ .Values.Block.InstanceId }}
    spec:
      k8sClusterSelector:
        matchLabels:
          site.nbycomp.com/{{ .Values.placement.site.label }}: "true"
      chart: {{ .Values.deployments.secretCreator.configuration.chart.name }}
      version: {{ .Values.deployments.secretCreator.configuration.chart.version }}
      repo:
        url: https://{{ .Values.deployments.secretCreator.configuration.chart.baseRegistryUrl }}/{{ .Values.deployments.secretCreator.configuration.chart.repo }}
        username: {{ .Values.deployments.secretCreator.configuration.chart.auth.username | quote }}
        password:
          secretKeyRef:
            name: {{ .Values.deployments.secretCreator.configuration.chart.auth.secret.name }}
            key: {{ .Values.deployments.secretCreator.configuration.chart.auth.secret.key }}
      values: |
        secrets:
          - name: {{ .Values.deployments.nginx.variables.imagePullSecret.name }}
            namespace: {{ .Values.deployments.nginx.variables.overrideNamespace | default .Release.Namespace }}
            type: data
            dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}
