{{- if .Values.connection.enabled }}
{{- if .Values.chart.values.ingress.enabled }}

apiVersion: blocks/v1beta1
kind: Connection
metadata:
  labels:
    type: coredns
    block: {{ .Values.Block.InstanceId }}
  name: dns-{{ .Values.Block.InstanceId }}
spec:
  value: |
    records:
      - 1.2.3.4 {{ .Values.chart.values.ingress.hostname }}

{{- end }}
{{- end }}
