apiVersion: v1
kind: Service
metadata:
  name: training-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
{{- range $i, $port := .Values.service.ports }}
    - protocol: TCP
      port: {{ $port }}
      targetPort: {{ $port }}
      name: {{ $.Values.service.commonString }}-{{ $i }}-{{ $port }}
{{- end }}      
