{{- if .Values.service.nodePort.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: training-service-nodeport
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort.port }}
{{- end }}
