{{- if .Values.deployments.nginx.configuration.chart.auth.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deployments.nginx.configuration.chart.auth.secret.name }}
{{- if .Values.deployments.nginx.variables.overrideNamespace }}
  namespace: {{ .Values.deployments.nginx.variables.overrideNamespace }}
{{- else }}
  namespace: {{ .Values.Block.InstanceId }}
{{- end }}
type: Opaque
stringData:
  {{ .Values.deployments.nginx.configuration.chart.auth.secret.key }}: {{ .Values.deployments.nginx.configuration.chart.auth.password }}

{{- end }}
